apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo
  name: mongo-newsvc
spec:
  ports:
  - port: 27017
    protocol: TCP
    targetPort: 27017
    nodePort: 31000
  selector:
    app: mongo
  type: NodePort
